### ISSUE TITLE
Missing function "getAllPossible5Kmers" in Models.PrepareData

### ISSUE THREAD

**Issue by Renown-TAL** [daniel235/Penguin#9]
Hello,
When I tried the Penguin, It show a error as following:

> File "/home/mjy/software/Penguin/main.py", line 119, in <module>
    Predict.nanopolish_predict(model, event_info, fastPath, bedPath, samPath, Idfile, testing=False)
  File "/home/mjy/software/Penguin/SignalExtractor/SignalPredictor.py", line 228, in nanopolish_predict
    allkmers = PD.getAllPossible5Kmers()
AttributeError: module 'Models.PrepareData' has no attribute 'getAllPossible5Kmers'

I read the PrepareData.py in folder Models and no 'getAllPossible5Kmers' inside.
Could you slove this problem?
Thanks a lot for you in advance.

**Comment by daniel235** [comment]
Finished kmers function.
